services:
  app:
    container_name: anonymous-chatting-frontend
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
