FROM node:22.16.0-alpine

WORKDIR /app

RUN npm install -g pnpm@10.11.0

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . . 

EXPOSE 3000
ENTRYPOINT [ "pnpm", "run" ]
CMD ["dev"]