import type { Metadata } from 'next';
import type { JSX } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="h-screen w-screen overflow-y-auto">{children}</div>
      </body>
    </html>
  );
}
